name: Release dev

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Clasp
        run: |
          npm install
          npm install clasp -g

      - name: Create clasprc.json
        run: |
          cat << EOS > ~/.clasprc.json
          {
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}"
              "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/script.deployments openid https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/userinfo.email",
              "token_type": "Bearer",
              "id_token": "${{ secrets.ID_TOKEN }}",
              "expiry_date": 1701482973427,
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS
      - name: Create clasp.json
        run: |
          cat << EOS > ~/.clasp.json
          {"scriptId": "${{ secrets.SCRIPT_ID_DEV }}"}
          EOS
      - name: Get running version
        run: |
          echo RUNNING_VERSION="$( clasp deployments | tail -n 1 | awk -F ' ' '{print $3}' )" >> $GITHUB_ENV

      - name: Publish
        run: clasp push -f

      - name: Deploy (Only first time)
        if: env.RUNNING_VERSION == '@HEAD'
        run: |
          clasp deploy -d $GITHUB_SHA

      - name: Deploy
        if: env.RUNNING_VERSION != '@HEAD'
        run: |
          DEPLOY_ID=$( clasp deployments | tail -n 1 | awk -F ' ' '{print $2}' )
          clasp deploy -d $GITHUB_SHA -i ${DEPLOY_ID}
